services:
  pruebaresto:
    build:
      context: .
      # secrets:
      # - db_username
      # - db_password
      # - db_database
      # - jwt_secret
    ports: 
      - "4000:4000"
    
    environment:
      - DB_HOST=aws-0-sa-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USERNAME=postgres.blrwfusxjepsuwbweokb
      - DB_PASSWORD='resto2024PF.'
      - DB_DATABASE=postgres
    # volumes:
    #   - ./secrets:/run/secrets
    # command: >
    #   sh -c "
    #     export DB_USERNAME=$$(cat /run/secrets/db_username.txt) &&
    #     export DB_PASSWORD=$$(cat /run/secrets/db_password.txt) &&
    #     export DB_DATABASE=$$(cat /run/secrets/db_database.txt) &&
    #     export JWT_SECRET=$$(cat /run/secrets/jwt_secret.txt) &&
    #     node dist/main.js
    #   "
# volumes:
#   secrets:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./secrets

# secrets:
#   db_username:
#     file: ./secrets/db_username.txt
#   db_password:
#     file: ./secrets/db_password.txt
#   db_database:
#     file: ./secrets/db_database.txt
#   jwt_secret:
#     file: ./secrets/jwt_secret.txt