name: deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{  secrets.DOCKERHUB_USERNAME  }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest-demo:latest
    -
      name: Deploy a Docker image to Render platform
        # You may pin to the exact commit or the version.
        # uses: gh-actions-workflows/deploy-docker-render@fa7e8b10359aac070427771b25fb9a0e0b0ae5e1
      uses: gh-actions-workflows/deploy-docker-render@v1.3
      with:
        deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
        image-url: ${{ secrets.DOCKERHUB_USERNAME }}/nest-demo:latest
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-deployment: true
